### ISSUE TITLE
The spacebar is not working if joystick mapping is set on cursor keys

### ISSUE THREAD

**Issue by foxp4v** [randyrossi/bmc64#40] opened 2019-04-22 21:48 UTC
As title, if joystick mapping is set to cursors+left ctrl or cursors+space the spacebar in basic is not working, instead if is mapped to numpad it works perfectly. Found this bug because i've had another strange problem, with the numpad mapping, for instance in the recently released Super Mario Bros, is impossible to jump while the fire button (used to run) is pressed, no problems with the cursor mapping instead.

**Comment by randyrossi** [comment] 2019-04-22 23:00
That's not a bug.  The same will happen if you map space to fire using any version of VICE.  The emulator has no way to know whether you are in basic or in a game.  Any custom key mapping will take that key input and use it for joystick.  The cursor + space option is just a convenient way to do a custom mapping.  

For the other issue, it's likely the case that your keyboard is not allowing both those keys to be pressed at the same time.  That's the limitation with using keyboards as joysticks.  Try using the same keyboard and same mapping on VICE using desktop version.

**Comment by foxp4v** [comment] 2019-04-22 23:41
Ok, but the same happens with cursor keys+left control.

**Comment by randyrossi** [comment] 2019-04-23 00:24
Not sure I follow.  Spacebar works fine in basic.  If you map space to fire, it will no longer be space.  The idea is you would only use that while within a game.

I tried both cntrl/space + cursor keys and I all joystick directions + fire map correctly for me.  Even two directions + fire works at the same time.

**Comment by foxp4v** [comment] 2019-04-23 08:24
I mean that mapping joystick to cursors+left control makes the spacebar not working in basic.

**Comment by randyrossi** [comment] 2019-04-24 13:11
Ah, I see now.  Thanks.

**Comment by lroby74** [comment] 2019-04-27 17:27
I've tried today.. IF i SET to cursors + space , in Basic space doesn't work because he's doing like fire of joystick but if i SET cursors + Left control then space bar will works like space bar in Basic and in games too

**Comment by foxp4v** [comment] 2019-04-27 22:48
Ok i've noticed that the issue is only when the joystick is mapped to port 2, when in port 1 works correctly. But i've found another little problem, don't know if open another ticket, i'll try to explain here: I'm on raspbery 2, on the first cold boot, very fast, the keyboard does not work, i have to turn off power then power on again and then it works again.

**Comment by lroby74** [comment] 2019-04-27 23:12
I know that an user modified one of 2 files for solve regular USB keyboard not working issue (don't remember if changed fast=true with #fast=true in cmdline.txt or boot_delay=0 in #boot_delay=0 in config.txt file)

**Comment by randyrossi** [comment] 2019-05-02 11:19
Should be fixed in 1.7

**Closed by randyrossi** 2019-05-02 11:19 UTC
